src=$(wildcard part*.cpp)
PARTS=$(src:%.cpp=%)

all: $(PARTS)

clean:
	$(RM) $(RF) $(PARTS)

part1: part1.cpp
	g++ part1.cpp -o part1
part2: part2.cpp
	g++ part2.cpp -o part2
part3: part3.cpp
	g++ part3.cpp -o part3
part4: part4.cpp
	g++ part4.cpp -o part4
part5: part5.cpp
	g++ part5.cpp -o part5

############### DON'T TOUCH BELOW ##################
run%: part%
	@./part$* || :

